### PR TITLE
Look for the package-under-development by name

### LINKED ISSUE #1596: Make custom `release_bullets()` more reliable
We've had multiple reports of `release_bullets()` not working the way people expect, i.e. not showing up in a package's release checklist (#1579, recent conversation in slack).

I am taking it as a given that we still expect a package to have been loaded with `load_all()`.

But even then, it's possible (likely?) for the `release_bullets()` to not be found.

The condition is that `release_bullets` is bound in the parent of global env:

https://github.com/r-lib/usethis/blob/2402ea8e4eb098b5fd18770174fa86ae1a803658/R/release.R#L121-L130

The intent is that the parent of global env will be the package-under-development.

But here's a simple demo where the first `load_all()` in a fresh R session has `devtools_shims` in that position. Only after the second `load_all()` do we fulfill the condition (and would find readr's custom release bullets).

cc @Hadley

``` r
Restarting R session...

> search()
 [1] ".GlobalEnv"         ".conflicts"         "tools:rstudio"      "package:graphics"  
 [5] "package:grDevices"  "package:utils"      "package:datasets"   "local:rprofile"    
 [9] "package:stats"      "package:pak"        "package:reprex"     "package:devtools"  
[13] "package:usethis"    "package:conflicted" "package:methods"    "Autoloads"         
[17] "org:r-lib"          "package:base"      

> devtools::load_all(".")
ℹ Loading readr

> search()
 [1] ".GlobalEnv"         "devtools_shims"     "package:readr"      "package:testthat"  
 [5] ".conflicts"         "tools:rstudio"      "package:graphics"   "package:grDevices" 
 [9] "package:utils"      "package:datasets"   "local:rprofile"     "package:stats"     
[13] "package:pak"        "package:reprex"     "package:devtools"   "package:usethis"   
[17] "package:conflicted" "package:methods"    "Autoloads"          "org:r-lib"         
[21] "package:base"     
 
> devtools::load_all(".")
ℹ Loading readr

> search()
 [1] ".GlobalEnv"         "package:readr"      "devtools_shims"     "package:testthat"  
 [5] ".conflicts"         "tools:rstudio"      "package:graphics"   "package:grDevices" 
 [9] "package:utils"      "package:datasets"   "local:rprofile"     "package:stats"     
[13] "package:pak"        "package:reprex"     "package:devtools"   "package:usethis"   
[17] "package:conflicted" "package:methods"    "Autoloads"          "org:r-lib"         
[21] "package:base"    
```

### PR DESCRIPTION
**Pull request by jennybc**
Closes #1596

### CODE REVIEW

File: R/release.R [hunk 1]
```diff
@@ -119,7 +119,15 @@ release_checklist <- function(version, on_cran) {
...
 }
 
-release_extra <- function(env = parent.env(globalenv())) {
+release_extra <- function(package = NULL) {
+  package <- package %||% project_name()
+  s <- search()
+  m <- match(paste0("package:", package), s)
+  if (is.na(m)) {
+    return(character())
+  }
```
Comment (jennybc) [inline R/release.R:128]: I'm not even sure how much we care about the package being attached? But this is the first time I've ever touched `release_extra()`, so maybe it is important?

**Comment by jennybc** [comment]
The tests (or implementation) would need to be adjusted, so consider this a sketch.

**Review by hadley — APPROVED** [review]
Yeah, that's even better!
