### PR TITLE
Ensure `cran_version()` does not fail when no internet or CRAN mirror is unset

### LINKED ISSUE #1857: `cran_version()` should be more robust
Several functions (`use_release_checklist()`, `use_news_md()`) call `cran_version()` to check if a package is on CRAN, which fails if a CRAN mirror is not set.

`cran_version()` calls `available.packages()` which in turn calls `contrib.url()` with `repos = getOption("repos")`. If the CRAN mirror is unset (the default value is `"@CRAN@"` in a factory fresh installation) it will prompt a user to choose in an interactive session, or fail otherwise:

``` r
withr::with_options(
  list(repos = c(CRAN = "@CRAN@")), 
  usethis:::cran_version()
)
#> Error in contrib.url(repos, type): trying to use CRAN without setting a mirror
```

This is showing up in revdep checks and CRAN checks for some usethis reverse depenencies which use `use_news_md()`. E.g., https://github.com/cynkra/fledge/issues/683

`cran_version()` should not fail if there is no internet, or if there is no CRAN mirror set. In the former case, it should likely return `NULL`, which it currently returns if the package is not on CRAN. That seems like a reasonable fallback. If there is no CRAN mirror set we should try to set one locally, and also wrap that in a `tryCatch()`, returning `NULL` again if still unsuccessful.

This was surfaced in revdepchecks for #1849, was at first thought to be a false positive, and did not cause issues on incoming checks, but is causing failures for revdeps on CRAN.

### PR DESCRIPTION
**Pull request by ateucher**
Fixes #1857.

This:

- Bails and returns `NULL` if offline.
- Passes `default_cran_version()` to the `repos` argument of `available.packages()` (this seemed more straightforward than setting local options). 
    - `default_cran_version()` is borrowed from [pak](https://github.com/r-lib/pak/blob/168ab5d58fc244e5084c2800c87b8a574d66c3ba/R/default-cran-mirror.R#L4), however I set the fallback mirror to `cloud.r-project.org` rather than `cran.rstudio.com`, which seems more canonical - but I'm happy to be re-educated. 
    - I modified `default_cran_version()` from pak to respect the users' other repos and append CRAN rather than replace the entire repos option with just CRAN. (As implemented in pak it only returns a CRAN repo, even if the user had other repos set in their `repos` option).
- The call to `available.packages()` is wrapped in a `try`, and returns `NULL` if it fails.

Do we want to emit any warnings or messages in case of the early returns of `NULL` (no internet or failure to check CRAN)?

### CODE REVIEW

File: R/release.R [hunk 1]
```diff
@@ -403,8 +403,25 @@ get_release_news <- function(SHA = gert::git_info(repo = git_repo())$commit,
...
-                         available = utils::available.packages()) {
+cran_version <- function(package = project_name(), available = NULL) {
+
+  if (!curl::has_internet()) {
+    return(NULL)
+  }
+
+  if (is.null(available)) {
+  # Guard against CRAN mirror being unset
+    available <- try(
```
Comment (jennybc) [inline R/release.R:414]: We sort of have a policy about never using `try()`, but instead using `tryCatch()`.

https://github.com/tidyverse/design/issues/85

Can you rewrite this using `tryCatch()`?

File: tests/testthat/test-release.R [hunk 2]
```diff
@@ -199,3 +199,38 @@ test_that("get_release_data() works for new-style CRAN-RELEASE", {
   expect_equal(res$SHA, HEAD)
   expect_equal(path_file(res$file), "CRAN-SUBMISSION")
 })
+
+test_that("cran_version() is robust to unset CRAN mirror with unreleased pkg (#1857)", {
+  create_local_package()
```
Comment (jennybc) [inline tests/testthat/test-release.R:204]: Instead of creating a local package, maybe we should just provide a nonsense package name to `cran_version()`, i.e. make this truly just a test of `cran_version()`.

File: tests/testthat/test-release.R [hunk 3]
```diff
@@ -199,3 +199,38 @@ test_that("get_release_data() works for new-style CRAN-RELEASE", {
   expect_equal(res$SHA, HEAD)
   expect_equal(path_file(res$file), "CRAN-SUBMISSION")
 })
+
+test_that("cran_version() is robust to unset CRAN mirror with unreleased pkg (#1857)", {
```
Comment (jennybc) [inline tests/testthat/test-release.R:203]:
```suggestion
test_that("cran_version() works for unreleased pkg with CRAN mirror set/unset (#1857)", {
```

File: tests/testthat/test-release.R [hunk 4]
```diff
@@ -199,3 +199,38 @@ test_that("get_release_data() works for new-style CRAN-RELEASE", {
...
+  create_local_package()
+
+  cran_repos <- list(
+    c(CRAN = "https://cloud.r-project.org"),
+    c(CRAN = "@CRAN@"),
+    c(CRAN = NA),
+    NULL
+  )
+
+  lapply(cran_repos, function(x) {
```
Comment (jennybc) [inline tests/testthat/test-release.R:213]: I have always found test failures inside this sort of a loop to be reported in a suboptimal way, although I haven't explored that space recently. But I'd be totally fine with doing this the "big and dumb" way, i.e. separate expectations, each inside a `withr::with_options()`.

File: tests/testthat/test-release.R [hunk 5]
```diff
@@ -199,3 +199,38 @@ test_that("get_release_data() works for new-style CRAN-RELEASE", {
...
+    withr::with_options(
+      list(repos = x),
+      expect_null(cran_version())
+    )
+  })
+})
+
+test_that("cran_version() is robust to unset CRAN mirror with released pkg (#1857)", {
```
Comment (jennybc) [inline tests/testthat/test-release.R:221]: This should gain `skip_if_offline()` (which also implies `skip_on_cran()`).

**Review by jennybc — COMMENTED** [review]
It would be interesting to rerun cloud checks for altdoc and fledge (if it's still possible to check against their non-updated versions) and see what happens.

**Comment by ateucher** [comment]
With these changes and running `revdepcheck::cloud_check(revdep_packages = c("fledge", "altdoc"))` I see:

```r
cloud_details(, "altdoc")
══ Reverse dependency check ══════════════════════════════════════════════════════════════════════════════════════════════════════════════ altdoc 0.2.1 ══

Status: OK

── Before ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
0 errors ✔ | 0 warnings ✔ | 0 notes ✔

── After ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
0 errors ✔ | 0 warnings ✔ | 0 notes ✔
``` 
 and

```r
cloud_details(, "fledge")
══ Reverse dependency check ══════════════════════════════════════════════════════════════════════════════════════════════════════════════ fledge 0.1.0 ══

Status: OK

── Fixed

✔ checking examples ... ERROR
✔ checking tests ... ERROR

── Before ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
❯ checking examples ... ERROR
  Running examples in ‘fledge-Ex.R’ failed
  The error most likely occurred in:
  
  > ### Name: bump_version
  > ### Title: Bump package version
  > ### Aliases: bump_version bump_version_impl
  > 
  > ### ** Examples
  > 
  > # Create mock package in a temporary directory.
  > # Set open to TRUE if you want to play in the mock package.
  > with_demo_project({
  +   # Use functions as if inside the newly created package project.
  +   # (Or go and actually run code inside the newly created package project!)
  +   # Add a new R file.
  +   usethis::use_r("cool-function", open = FALSE)
  +   # Pretend we added useful code inside it.
  +   # Track the new R file with Git.
  +   gert::git_add("R/cool-function.R")
  +   gert::git_commit("- Add cool function.")
  +   # Bump version with fledge.
  +   fledge::bump_version()
  + })
  sh: 1: git: not found
  sh: 1: git: not found
  sh: 1: git: not found
  sh: 1: git: not found
  Error in contrib.url(repos, type) : 
    trying to use CRAN without setting a mirror
  Calls: with_demo_project ... <Anonymous> -> cran_version -> <Anonymous> -> contrib.url
  Execution halted

❯ checking tests ... ERROR
  See below...

── Test failures ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── testthat ────

> if (require(testthat)) {
+   library(fledge)
+   test_check("fledge")
+ } else {
+   message("testthat not available.")
+ }
Loading required package: testthat
sh: 1: git: not found
sh: 1: git: not found
sh: 1: git: not found
sh: 1: git: not found
sh: 1: git: not found
sh: 1: git: not found
sh: 1: git: not found
sh: 1: git: not found
sh: 1: git: not found
sh: 1: git: not found
sh: 1: git: not found
sh: 1: git: not found
sh: 1: git: not found
sh: 1: git: not found
sh: 1: git: not found
sh: 1: git: not found
sh: 1: git: not found
sh: 1: git: not found
sh: 1: git: not found
sh: 1: git: not found
sh: 1: git: not found
sh: 1: git: not found
sh: 1: git: not found
sh: 1: git: not found
sh: 1: git: not found
sh: 1: git: not found
sh: 1: git: not found
sh: 1: git: not found
[ FAIL 8 | WARN 0 | SKIP 5 | PASS 0 ]

══ Skipped tests ═══════════════════════════════════════════════════════════════
• On CRAN (4)
• On Linux (1)

══ Failed tests ════════════════════════════════════════════════════════════════
── Error ('test-bump_version.R:5:3'): bump_version() works -- dev ──────────────
Error in `contrib.url(repos, type)`: trying to use CRAN without setting a mirror
Backtrace:
    ▆
 1. └─fledge::with_demo_project(...) at test-bump_version.R:5:2
 2.   └─fledge::create_demo_project(dir = dir, news = TRUE)
 3.     ├─usethis::with_project(...)
 4.     │ └─base::force(code)
 5.     ├─rlang::with_interactive(...)
 6.     └─usethis::use_news_md()
 7.       └─usethis:::cran_version()
 8.         └─utils::available.packages()
 9.           └─utils::contrib.url(repos, type)
── Error ('test-bump_version.R:26:3'): bump_version() works -- not dev ─────────
Error in `contrib.url(repos, type)`: trying to use CRAN without setting a mirror
Backtrace:
    ▆
 1. └─fledge::with_demo_project(...) at test-bump_version.R:26:2
 2.   └─fledge::create_demo_project(dir = dir, news = TRUE)
 3.     ├─usethis::with_project(...)
 4.     │ └─base::force(code)
 5.     ├─rlang::with_interactive(...)
 6.     └─usethis::use_news_md()
 7.       └─usethis:::cran_version()
 8.         └─utils::available.packages()
 9.           └─utils::contrib.url(repos, type)
── Error ('test-bump_version.R:44:3'): bump_version() errors informatively for forbidden notifications ──
Error in `contrib.url(repos, type)`: trying to use CRAN without setting a mirror
Backtrace:
    ▆
 1. └─fledge::with_demo_project(...) at test-bump_version.R:44:2
 2.   └─fledge::create_demo_project(dir = dir, news = TRUE)
 3.     ├─usethis::with_project(...)
 4.     │ └─base::force(code)
 5.     ├─rlang::with_interactive(...)
 6.     └─usethis::use_news_md()
 7.       └─usethis:::cran_version()
 8.         └─utils::available.packages()
 9.           └─utils::contrib.url(repos, type)
── Error ('test-bump_version.R:54:3'): bump_version() errors informatively for wrong branch ──
Error in `contrib.url(repos, type)`: trying to use CRAN without setting a mirror
Backtrace:
    ▆
 1. └─fledge::with_demo_project(...) at test-bump_version.R:54:2
 2.   └─fledge::create_demo_project(dir = dir, news = TRUE)
 3.     ├─usethis::with_project(...)
 4.     │ └─base::force(code)
 5.     ├─rlang::with_interactive(...)
 6.     └─usethis::use_news_md()
 7.       └─usethis:::cran_version()
 8.         └─utils::available.packages()
 9.           └─utils::contrib.url(repos, type)
── Error ('test-finalize-version.R:4:3'): finalize_version(push = FALSE) ───────
Error in `contrib.url(repos, type)`: trying to use CRAN without setting a mirror
Backtrace:
    ▆
 1. └─fledge::with_demo_project(...) at test-finalize-version.R:4:2
 2.   └─fledge::create_demo_project(dir = dir, news = TRUE)
 3.     ├─usethis::with_project(...)
 4.     │ └─base::force(code)
 5.     ├─rlang::with_interactive(...)
 6.     └─usethis::use_news_md()
 7.       └─usethis:::cran_version()
 8.         └─utils::available.packages()
 9.           └─utils::contrib.url(repos, type)
── Error ('test-finalize-version.R:27:3'): finalize_version(push = TRUE) ───────
Error in `contrib.url(repos, type)`: trying to use CRAN without setting a mirror
Backtrace:
    ▆
 1. └─fledge::with_demo_project(...) at test-finalize-version.R:27:2
 2.   └─fledge::create_demo_project(dir = dir, news = TRUE)
 3.     ├─usethis::with_project(...)
 4.     │ └─base::force(code)
 5.     ├─rlang::with_interactive(...)
 6.     └─usethis::use_news_md()
 7.       └─usethis:::cran_version()
 8.         └─utils::available.packages()
 9.           └─utils::contrib.url(repos, type)
── Error ('test-tag_version.R:2:3'): tag_version() works ───────────────────────
Error in `contrib.url(repos, type)`: trying to use CRAN without setting a mirror
Backtrace:
    ▆
 1. └─fledge::with_demo_project(...) at test-tag_version.R:2:2
 2.   └─fledge::create_demo_project(dir = dir, news = TRUE)
 3.     ├─usethis::with_project(...)
 4.     │ └─base::force(code)
 5.     ├─rlang::with_interactive(...)
 6.     └─usethis::use_news_md()
 7.       └─usethis:::cran_version()
 8.         └─utils::available.packages()
 9.           └─utils::contrib.url(repos, type)
── Error ('test-unbump_version.R:4:3'): unbump_version() works ─────────────────
Error in `contrib.url(repos, type)`: trying to use CRAN without setting a mirror
Backtrace:
    ▆
 1. └─fledge::create_demo_project(...) at test-unbump_version.R:4:2
 2.   ├─usethis::with_project(...)
 3.   │ └─base::force(code)
 4.   ├─rlang::with_interactive(...)
 5.   └─usethis::use_news_md()
 6.     └─usethis:::cran_version()
 7.       └─utils::available.packages()
 8.         └─utils::contrib.url(repos, type)

[ FAIL 8 | WARN 0 | SKIP 5 | PASS 0 ]
Deleting unused snapshots:
• bump_version/NEWS-nondev.md
• bump_version/NEWS.md
• finalize-version/NEWS-push-false.md
• finalize-version/NEWS-push-true.md
• unbump_version/NEWS.md
• update-news/NEWS-empty.md
• update-news/NEWS-new.md
Error: Test failures
Execution halted

2 errors ✖ | 0 warnings ✔ | 0 notes ✔

── After ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
0 errors ✔ | 0 warnings ✔ | 0 notes ✔
```

File: R/release.R (hunk 1 above)
Comment (ateucher) [reply R/release.R:414]: Ok! I had looked in the design guide about this, but not in the issues ;)

File: tests/testthat/test-release.R (hunk 2 above)
Comment (ateucher) [reply tests/testthat/test-release.R:204]: Hoping that no one releases a package with that name ;)

File: R/release.R (hunk 1 above)
Comment (jennybc) [reply R/release.R:414]: Well, this is more folklore at this point. It needs to be written up properly.

**Comment by jennybc** [comment]
What do you make of those cloud check results?

**Comment by ateucher** [comment]
> What do you make of those cloud check results?

altdoc did a release in which [they set the cran mirror](https://github.com/etiennebacher/altdoc/commit/ef86ea7508f53483a8e2f07ee73d3748d512d10a), so the before and after both being clean is expected I think.

For fledge, it looks like this fixes it - failed tests with `Error in `contrib.url(repos, type)`: trying to use CRAN without setting a mirror` in the Before, but clean in the After. I don't know what to make of the `git not found` messages...

**Comment by jennybc** [comment]
Ah, re: fledge I completely missed that we were looking at Before vs. After. So that's great.

**Review by jennybc — APPROVED** [review]
LGTM

My parting thought is that it's within our control to differentiate "we don't know if this package is on CRAN" from "we're pretty damn sure this package is not on CRAN", but currently we conflate them.

However, given our current use of `cran_version()` this is probably fine.

**Comment by ateucher** [comment]
Yeah, absolutely. Would have to think about what to do with that information (not on CRAN vs don't know) in the functions that call it - `use_news_md()` and `use_release_issue()`.
