### PR TITLE
Ensure src/ always has a code file (#720)

### LINKED ISSUE #720: Fail to build/document after usethis::use_rcpp() with empty src/
The sequence `usethis::use_rcpp()`, then "Clean and Rebuild", then `devtools::document()` fails with

```R
Error in getDLLRegisteredRoutines.DLLInfo(dll, addNames = FALSE) :  must specify DLL via a “DLLInfo” object. See getLoadedDLLs()
```

apparently, because "src/" contains no "file.cpp".

I expected this to work, maybe by automatically adding a src/toy-file.cpp. Or I expected a message with the following TODO items:

* Add at least one .cpp file into src/
* Clean and Reload
* `devtools::document()`

Below is a sequence starting from a fresh package, leading to the problem, then solving it.

<details>
    <summary>Details</summary>

```r
# On a separate sassion
usethis::create_package("~/abc")

# New session
usethis::use_package_doc()
usethis::use_roxygen_md()
usethis::use_rcpp()
```

R/abc-package.R now looks like this:

``` r
#' @keywords internal
"_PACKAGE"

# The following block is used by usethis to automatically manage
# roxygen namespace tags. Modify with care!
## usethis namespace: start
#' @useDynLib abc, .registration = TRUE
#' @importFrom Rcpp sourceCpp
## usethis namespace: end
NULL
```

### Problem

```R
devtools::document()
Updating abc documentation
Writing NAMESPACE
Loading abc
Error in getDLLRegisteredRoutines.DLLInfo(dll, addNames = FALSE) : 
  must specify DLL via a “DLLInfo” object. See getLoadedDLLs()
Call `rlang::last_error()` to see a backtrace
```

Clean and Rebuild also fails

### Solution 

```r
usethis::use_rcpp("toy")
```

Now I can 'Clean and Rebuild'

And I can also document

```R
devtools::document()
Updating abc documentation
Loading abc
Writing abc-package.Rd
```

Info

``` r
sessioninfo::session_info()
#> - Session info ----------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.5.3 (2019-03-11)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  ctype    English_United States.1252  
#>  tz       America/New_York            
#>  date     2019-04-19                  
#> 
#> - Packages --------------------------------------------------------------
#>  package     * version date       lib source        
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.5.3)
#>  cli           1.1.0   2019-03-19 [1] CRAN (R 3.5.3)
#>  crayon        1.3.4   2017-09-16 [1] CRAN (R 3.5.2)
#>  digest        0.6.18  2018-10-10 [1] CRAN (R 3.5.2)
#>  evaluate      0.13    2019-02-12 [1] CRAN (R 3.5.2)
#>  highr         0.8     2019-03-20 [1] CRAN (R 3.5.3)
#>  htmltools     0.3.6   2017-04-28 [1] CRAN (R 3.5.2)
#>  knitr         1.22    2019-03-08 [1] CRAN (R 3.5.2)
#>  magrittr      1.5     2014-11-22 [1] CRAN (R 3.5.2)
#>  Rcpp          1.0.1   2019-03-17 [1] CRAN (R 3.5.3)
#>  rmarkdown     1.12    2019-03-14 [1] CRAN (R 3.5.2)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.5.2)
#>  stringi       1.4.3   2019-03-12 [1] CRAN (R 3.5.3)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 3.5.2)
#>  withr         2.1.2   2018-03-15 [1] CRAN (R 3.5.2)
#>  xfun          0.6     2019-04-02 [1] CRAN (R 3.5.3)
#>  yaml          2.2.0   2018-07-25 [1] CRAN (R 3.5.2)
#> 
#> [1] C:/Users/LeporeM/Documents/R/win-library/3.5
#> [2] C:/Users/LeporeM/Documents/R/R-3.5.3/library
```

Created on 2019-04-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

</details>

### PR DESCRIPTION
**Pull request by coatless**
Fixes #720

This PR modifies both `use_rcpp()` and `use_c()` to ensure at least one source file is present in `src/`. Previously, if a source file wasn't present but the `src/` directory was, then the package would error on build.

In addition, this PR adds two new functions into the `directory.R` variant related to counting files in a directory.

### CODE REVIEW

**Comment by coatless** [comment]
@jennybc thoughts on this one for #720 ?

**Comment by jennybc** [comment]
As for the file to add, will you do *RStudio > File > New Project > New Directory > R Package using Rcpp* and tell me what you think of what it leaves behind in `src/`?

`rcpp_hello_world.cpp` looks pretty good to me.

File: R/rcpp.R [hunk 1]
```diff
@@ -109,3 +107,18 @@ use_makevars <- function(settings = NULL) {
     edit_file(makevars_win_path)
   }
 }
+
+use_src_example_script <- function(name, src_type = c("cpp", "c") ) {
+
+  src_type = match.arg(src_type)
+
+  if (is.null(name) && !check_directory_has_files(path("src"))) {
```
Comment (jennybc) [inline R/rcpp.R]: I'm surprised this works because our checkers, in general, either don't return anything or return their input. In general, they don't return logical.

I'm happy to take a turn with this (fiddle with directory utilities, that aren't just for this) and then push a few commits in and see if you like it. Sound ok?

Comment (coatless) [reply R/rcpp.R]: Sounds perfect. Though, I did add `check_direct_has_files()`, c.f. https://github.com/r-lib/usethis/pull/860/commits/6957e4836dc74f0e6ef6696a6d4ac61438817714

**Comment by coatless** [comment]
@jennybc I'm hesitant to pre-populate the default RStudio file for Rcpp as the current _C++_ file is generic and sparse. This file would be used if either `use_rcpp()`, `use_rcpp_armadillo()`, or `use_rcpp_eigen()` was called. If you feel this would be best, then I'm happy to make change.

File: R/rcpp.R (hunk 1 above)
Comment (jennybc) [reply R/rcpp.R]: OK I'll make some changes in this PR and tag you to take a look.

File: R/rcpp.R [hunk 2]
```diff
@@ -1,10 +1,20 @@
 #' Use C, C++, RcppArmadillo, or RcppEigen
 #'
-#' Creates `src/`, adds required packages to `DESCRIPTION`,
-#' optionally creates `.c` or `.cpp` files, and
-#' where needed, `Makevars` and `Makevars.win` files.
+#' Adds infrastructure commonly needed when using compiled code:
+#'   * Creates `src/`
+#'   * Adds required packages to `DESCRIPTION`
+#'   * May create an initial placeholder `.c` or `.cpp` file
+#'   * Creates `Makevars` and `Makevars.win` files (`use_rcpp_armadillo()` only)
```
Comment (jennybc) [inline R/rcpp.R]: I think bullets are clearer for this.

File: R/rcpp.R [hunk 3]
```diff
@@ -58,22 +63,17 @@ use_rcpp_eigen <- function(name = NULL) {
...
 #' @export
 use_c <- function(name = NULL) {
-  use_src()
+  check_is_package("use_c()")
+  check_uses_roxygen("use_c()")
 
-  if (!is.null(name)) {
-    name <- slug(name, "c")
-    check_file_name(name)
+  use_src()
```
Comment (jennybc) [inline R/rcpp.R]: Just some mundane maintenance/refactoring. Makes `use_c()` more similar to `use_rcpp()` and means if these checks fail, the error message makes more sense.

File: R/rcpp.R [hunk 4]
```diff
@@ -58,22 +63,17 @@ use_rcpp_eigen <- function(name = NULL) {
...
-  }
+  use_src_example_script(name, "c")
 
   invisible(TRUE)
 }
 
 use_src <- function() {
-  check_is_package("use_src()")
-  check_uses_roxygen("use_rcpp()")
-
```
Comment (jennybc) [inline R/rcpp.R]: If necessary, caller does this.

**Comment by jennybc** [comment]
@coatless See what you think.

File: R/rcpp.R (hunk 2 above)
Comment (coatless) [reply R/rcpp.R]: Agreed.

File: R/rcpp.R (hunk 3 above)
Comment (coatless) [reply R/rcpp.R]: This makes perfect sense.

**Comment by coatless** [comment]
@jennybc makes complete sense to me. I agree with all of the changes.

**Comment by jennybc** [comment]
Great, here we go!

**Comment by coatless** [comment]
👍 thanks again @jennybc.
